cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout')
]

products/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.products,
         name='products'
         ),
    path('category/<slug:category_slug>/',
         views.products,
         name='products_by_category'
         ),
    path('category/<slug:category_slug>/<slug:product_slug>/',
         views.product_detail,
         name='product_detail'
         ),
    path('search/', views.search,
         name='search'
         ),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from products.models import Product, Variation
from accounts.models import Account


#___________________________________________________________  Cart
class Cart(models.Model):
    '''
    Stores information about the user's shopping cart, including the cart ID and the date
    when it was added.
    '''
    cart_id     = models.CharField(max_length=250, blank=True)
    date_added  = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id
    

#___________________________________________________________  CartItem
class CartItem(models.Model):
    '''
    Stores information about an item added to a shopping cart, including the associated
    user, product, variations, cart, quantity, and whether the item is active.
    '''
    user        = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product     = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations  = models.ManyToManyField(Variation, blank=True)
    cart        = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity    = models.IntegerField()
    is_active   = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

products/models.py
from django.db import models
from category.models import Category
from django.urls import reverse


#___________________________________________________________  Product
class Product(models.Model):
      '''
      Model representing a product.
      '''
      product_name      = models.CharField(max_length=200, unique=True)
      slug              = models.SlugField(max_length=200, unique=True)
      description       = models.TextField(max_length=500, blank=True)
      price             = models.IntegerField()
      images            = models.ImageField(upload_to='photos/products')
      stock             = models.IntegerField()
      is_available      = models.BooleanField(default=True)
      category          = models.ForeignKey(Category, on_delete=models.CASCADE)
      created_date      = models.DateTimeField(auto_now_add=True)
      modified_date     = models.DateTimeField(auto_now=True)

      def get_url(self):
            return reverse('product_detail', args=[self.category.slug, self.slug])

      def __str__(self):
            return self.product_name


#___________________________________________________________  VariationManager
class VariationManager(models.Manager):
      '''
      Custom manager for variations.
      '''
      def colors(self):
            return super(VariationManager, self).filter(
                  variation_category='color',
                  is_active=True
            )
      
      def sizes(self):
            return super(VariationManager, self).filter(
                  variation_category='size',
                  is_active=True
            )

variation_category_choice = (
      ('color', 'color'),
      ('size', 'size'),
)


#___________________________________________________________  Variation
class Variation(models.Model):
      '''
      Model for product variations.
      '''
      product = models.ForeignKey(Product, on_delete=models.CASCADE)
      variation_category = models.CharField(
            max_length=100, choices=variation_category_choice
            )
      variation_value = models.CharField(max_length=100)
      is_active = models.BooleanField(default=True)
      created_date = models.DateTimeField(auto_now=True)
      objects = VariationManager()

      def __str__(self):
            return self.variation_value

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from products.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required


#___________________________________________________________  _CART_ID
def _cart_id(request):
    '''
    Helper function to retrieve or create a unique cart ID for the current session.
    '''
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


#___________________________________________________________  ADD_CART
def add_cart(request, product_id):
    '''
    Function handles the addition of a product to the shopping cart. If the user is
    authenticated, it adds the product to the cart associated with the user. If the user is not
    authenticated, it adds the product to the session-based cart.
    '''
    current_user = request.user
    product = Product.objects.get(id=product_id)
    # If user is authenticated
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # Increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                user = current_user,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')
    # If user is not authenticated
    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            # Existing_variations > Database
            # Current_varations > Product_variation
            # Item_id > database
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            print(ex_var_list)

            if product_variation in ex_var_list:
                # Increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            
            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')


#___________________________________________________________  REMOVE_CART
def remove_cart(request, product_id, cart_item_id):
    '''
    Function to remove a product from the shopping cart.
    '''
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


#___________________________________________________________  remove_cart_item
def remove_cart_item(request, product_id, cart_item_id):
    '''
    Function to remove a specific cart item from the shopping cart.
    '''
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')


#___________________________________________________________  cart
def cart(request, total=0, quantity=0, cart_items=None):
    '''
    Function calculates the total price, quantity, tax, and grand total of items in the shopping cart.
    If the user is authenticated, it retrieves cart items associated with the user. 
    If the user is not authenticated, it retrieves cart items from the session-based cart.
    '''
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context  = {
        'total':  total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax' : tax,
        'grand_total': grand_total,
    }
    return render(request, 'products/cart.html', context)


#___________________________________________________________  checkout
@login_required(login_url='signin')
def checkout(request, total=0, quantity=0, cart_items=None):
    '''
    Function to process the checkout of items in the shopping cart.
    '''
    try:
        tax = 0
        grand_total = 0
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass #just ignore

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax' : tax,
        'grand_total': grand_total,
    }
    return render(request, 'products/checkout.html', context)

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product
from category.models import Category
from cart.models import CartItem
from django.db.models import Q

from cart.views import _cart_id
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from orders.models import OrderProduct
from django.http import HttpResponse
from django.contrib import messages


#___________________________________________________________  products
def products(request, category_slug=None):
    '''
    Displays products based on the selected category slug.
    If no category is selected, displays all available products paginated.
    '''
    categories = None
    products = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()

    context = {
        'products': paged_products,
        'product_count': product_count,
    }
    return render(request, 'products/products.html', context)


#___________________________________________________________  product_detail
def product_detail(request, category_slug, product_slug):
    '''
    Displays the details of a single product identified by its category slug
    and product slug.
    '''
    try:
        single_product = Product.objects.get(category__slug=category_slug,slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request),product=single_product).exists()
    except Exception as e:
        raise e
    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user=request.user,product_id=single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None
    
    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'orderproduct': orderproduct,
    }
    return render(request, 'products/product_detail.html', context)


#___________________________________________________________  search
def search(request):
    '''
    Searches for products based on the provided keyword
    in the request GET parameters.
    '''
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()
    context = {
        'products': products,
        'product_count': product_count,
    }
    return render(request, 'products/products.html', context)

templates/products/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
        {% if not cart_items %}
            <h2 class="text-center">Your Cart is empty</h2>
            <br>
            <div class="text-center">
                <a href="{% url 'products' %}" class="btn btn-primary">Continue Shopping</a>
            </div>
        {% else %}
        <div class="row">
            <aside class="col-lg-9">
                <div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                                            <p class="text-muted small">
                                                {% if cart_item.variations.all %}
                                                    {% for item in cart_item.variations.all %}
                                                        {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
                                                    {% endfor %}
                                                {% endif %}
                                            </p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-append">
                                                <a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}"
                                                class="btn btn-light" type="button" id="button-plus"><i class="fa fa-minus"></i>
                                                </a>
                                            </div>
                                            <input type="text" class="form-control" value="{{ cart_item.quantity }}">
                                            <div class="input-group-prepend">
                                                <form action="{% url 'add_cart' cart_item.product.id %}" method="POST">
                                                    {% csrf_token %}
                                                    {% for item in cart_item.variations.all %}
                                                        <input type="hidden" name="{{ item.variation_category | lower }}" value="{{ item.variation_value | capfirst }}">
                                                    {% endfor %}
                                                    <button class="btn btn-light" type="submit" id="button-minus"><i class="fa fa-plus"></i></button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">${{ cart_item.sub_total }}</var>
                                        <small class="text-muted">${{ cart_item.product.prize }} each </small>
                                    </div>
                                </td>
                                <td class="text-right">
                                    <a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('Are you sure you want to delete this item?')"
                                        class="btn btn-danger"> Remove
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </aside>
            <aside class="col-lg-3">
                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Total price:</dt>
                            <dd class="text-right">${{total}}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Tax:</dt>
                            <dd class="text-right">${{tax}}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Grand Total:</dt>
                            <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="{% static './images/misc/payments.png' %}" height="26">
                        </p>
                        <a href="{% url 'checkout' %}" class="btn btn-primary btn-block">Checkout</a>
                        <a href="{% url 'products' %}" class="btn btn-light btn-block">Continue Shopping</a>
                    </div>
                </div>
            </aside>
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}

templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
        <div class="card">
            <div class="row no-gutters">
                <aside class="col-md-6">
                    <article class="gallery-wrap"> 
                        <div class="img-big-wrap">
                            <a href="#"><img src="{{ single_product.images.url }}"></a>
                        </div>
                    </article>
                </aside>
                <main class="col-md-6 border-left">
                    <form action="{% url 'add_cart' single_product.id %}" method="POST">
                        {% csrf_token %}
                        <article class="content-body">
                            <h2 class="title">{{ single_product.product_name }}</h2>
                            <!-- Rating was supposed to be here :( -->
                            <div class="mb-3">
								<var class="price h4">$ {{single_product.price}}</var>
							</div>
							<p>{{ single_product.description }}</p>
							<hr>
							<div class="row">
								<div class="item-option-select">
									<h6>Choose Color</h6>
									<select name="color" class="form-control" required>
										<option value="" disabled selected>Select</option>
										{% for variation in single_product.variation_set.colors %}
										<option value="{{ variation.variation_value }}">{{ variation.variation_value }}</option>
										{% endfor %}
									</select>
								</div>
							</div>
							<div class="row">
								<div class="item-option-select">
									<h6>Select Size</h6>
									<select name="size" class="form-control">
										<option value="" disabled selected>Select</option>
										{% for variation in single_product.variation_set.sizes %}
										<option value="{{ variation.variation_value }}">{{ variation.variation_value }}</option>
										{% endfor %}
									</select>
								</div>
							</div>
                            <hr>
                            {% if single_product.stock <= 0 %}
                            <h5 class="text-danger">Out of Stock</h5>
                            {% else %}
                            <button type="submit" class="btn btn-primary"><span class="text">Add to cart</span><i class="fas fa-shopping-cart"></i></button>
                            {% endif %}
                        </article>
                    </form>
                </main>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-9">
                <header class="section-heading">
                    <h3>Customer Reviews</h3>  
                </header>
                <article class="box mb-3">
                    <div class="icontext w-100">
                        <img src="{% static 'images/avatars/avatar1.png' %}" class="img-xs icon rounded-circle">
                        <div class="text">
                            <span class="date text-muted float-md-right">11.05.2020 </span>  
                            <h6 class="mb-1">Elton john</h6>
                        </div>
                    </div>
                    <div class="mt-3">
                        <p>Great Service, Great Clothes and Great Prices! I´ll buy everything from I SHOP from now on!!!</p>    
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/products/products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section-pagetop bg">
    <div class="container">
        {% if 'search' in request.path %}
            <h2 class="title-page">Search Results</h2>
        {% else %}
            <h2 class="title-page">Our Products:</h2>
        {% endif %}
    </div>
</section>
<section class="section-content padding-y">
    <div class="container">
        <div class="row">
            <aside class="col-md-3">
                <div class="card">
                    <article class="filter-group">
                        <header class="card-header">
                            <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                                <i class="icon-control fa fa-chevron-down"></i>
                                <h6 class="title">Categories</h6>
                            </a>
                        </header>
                        <div class="filter-content collapse show" id="collapse_1" style="">
                            <div class="card-body">
                                <ul class="list-menu">
                                    <li><a href="{% url 'products' %}">All Products</a></li>
                                    {% for category in links %}
                                    <li><a href="{{ category.get_url }}">{{ category.category_name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </article>
                </div>
            </aside>
            <main class="col-md-9">
                <header class="border-bottom mb-4 pb-3">
                    <div class="form-inline">
                        <span class="mr-md-auto"><strong>{{ product_count }}</strong> products</span>
                    </div>
                </header>
                <div class="row">
                    {% if products %}
                    {% for product in products %}
                    <div class="col-md-4">
                        <figure class="card card-product-grid">
                            <div class="img-wrap">
                                <a href="{{ product.get_url }}"><img src="{{ product.images.url }}"></a>
                            </div>
                            <figcaption class="info-wrap">
                                <div class="fix-height">
                                    <a href="{{ product.get_url }}" class="title">{{ product.product_name }}</a>
                                    <div class="price-wrap mt-2">
                                        <span class="price">${{ product.price }}</span>
                                    </div>
                                </div>
                                <a href="{{ product.get_url }}" class="btn btn-block btn-primary">View Details</a>
                            </figcaption>
                        </figure>
                    </div>
                    {% endfor %}
                    {% else %}
                    <div>
                        <h2>No Results</h2>
                    </div>
                    {% endif %}
                </div>
                <nav class="mt-4" aria-label="Page navigation sample">
                    {% if products.has_other_pages %}
                        <ul class="pagination">
                            {% if products.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a></li>
                            {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                            {% endif %}

                            {% for i in products.paginator.page_range %}
                                {% if products.number == i %}
                                <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
                                {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if products.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{products.next_page_number}}">Next</a></li>
                            {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </nav>
            </main>
        </div>
    </div>
</section>
{% endblock %}